import 'package:sqflite/sqflite.dart';
import 'package:sqflite_common_ffi_web/sqflite_ffi_web.dart';

/// Web: sqflite has no native platform implementation, so route it through the
/// IndexedDB-backed FFI-web factory. Requires `sqflite_sw.js` + `sqlite3.wasm`
/// in the web build output (generated by `dart run sqflite_common_ffi_web:setup`).
void configureDatabaseFactoryForWeb() {
  databaseFactory = databaseFactoryFfiWeb;
}
